### ISSUE TITLE
more async

### ISSUE THREAD

**Issue by raaiider** [Conclure/DeluxeAsyncJoinLeaveMessage#2]
more async

**Comment by conclube** [comment]
Hi my guy, today is the end of the synchronous programming. The end of a developing technique that acquiesces to disorder. At this very moment in a system far from here, the Bukkit API lies to the galaxy while secretly supporting the treachery of the loathsome synchronous programming. This fierce code which I have built, upon which I stand will bring an end to synchronous programming, to their cherished synchronous scheduler. All remaining systems will bow to the asynchronous programming and will remember this as the last day of the Bukkit API!
